### ISSUE TITLE
Portal does not start

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_portal8#100]
Installing a new version of the portal on a newly installed js8 works fine but the portal does not start.
Looking at the logs, the following error can be found
```
Nov 25 16:26:36 vm-3908 jspython[27356]: /bin/bash: warning: setlocale: LC_ALL: cannot change locale ('C.UTF-8'TERM='xterm-vt220'LANG='C.UTF-8'CODEDIR='/opt/code'LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01
Nov 25 16:26:36 vm-3908 jspython[27356]: ale8/lib/lua/?/?.lua;/opt/jumpscale8/lib/): Invalid argument
Nov 25 16:26:36 vm-3908 jspython[27356]: Error in sys.excepthook:
Nov 25 16:26:36 vm-3908 jspython[27356]: Traceback (most recent call last):
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<frozen importlib._bootstrap>", line 693, in _load
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/data/idgenerator/IDGenerator.py", line 2, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:     from JumpScale import j
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/__init__.py", line 207, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:     j.application.init()
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/core/main/Application.py", line 124, in init
Nov 25 16:26:36 vm-3908 jspython[27356]:     j.dirs.init()
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/__init__.py", line 81, in __getattr__
Nov 25 16:26:36 vm-3908 jspython[27356]:     obj = eval("obj0.%s()" % classname)
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<string>", line 1, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/core/main/Dirs.py", line 41, in __init__
Nov 25 16:26:36 vm-3908 jspython[27356]:     self.homeDir = os.environ["HOME"]
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/usr/lib/python3.5/os.py", line 725, in __getitem__
Nov 25 16:26:36 vm-3908 jspython[27356]:     raise KeyError(key) from None
Nov 25 16:26:36 vm-3908 jspython[27356]: KeyError: 'HOME'
Nov 25 16:26:36 vm-3908 jspython[27356]: Original exception was:
Nov 25 16:26:36 vm-3908 jspython[27356]: Traceback (most recent call last):
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "portal_start.py", line 9, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:     from JumpScale import j
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8/lib/JumpScale/__init__.py", line 207, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:     j.application.init()
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/core/main/Application.py", line 124, in init
Nov 25 16:26:36 vm-3908 jspython[27356]:     j.dirs.init()
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8/lib/JumpScale/__init__.py", line 81, in __getattr__
Nov 25 16:26:36 vm-3908 jspython[27356]:     obj = eval("obj0.%s()" % classname)
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "<string>", line 1, in <module>
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/opt/jumpscale8//lib/JumpScale/core/main/Dirs.py", line 41, in __init__
Nov 25 16:26:36 vm-3908 jspython[27356]:     self.homeDir = os.environ["HOME"]
Nov 25 16:26:36 vm-3908 jspython[27356]:   File "/usr/lib/python3.5/os.py", line 725, in __getitem__
Nov 25 16:26:36 vm-3908 jspython[27356]:     raise KeyError(key) from None
Nov 25 16:26:36 vm-3908 jspython[27356]: KeyError: 'HOME'
```

**Comment by ahussein** [comment]
It looks like there is a problem parsing the environment variables from the bash js tool
`Nov 26 13:50:29 vm-3918 systemd[1]: [/etc/systemd/system/portal.service:10] Invalid environment assignment, ignoring: LESSOPEN='| /usr/bin/lesspipe %s':k8='\E[19~:k9=\E[20~:k;=\E[21~:F1=\E[23~:F2=\E[24~:\':ku='\EOA:kd=\EOB:kr`

The reason for that is how the code for the bash tool is parsing the environment variables:
```
    @property
    def environ(self):
        if self._environ == {}:
            res = {}
            for line in self._cuisine.core.run("printenv", profile=True, showout=False)[1].splitlines():
                if '=' in line:
                    name, val = line.split("=", 1)
                    name = name.strip()
                    val = val.strip().strip("'").strip("\"")
                    res[name] = val
            self._environ = res
        merge = self._environ.copy()
        merge.update(self.profile.environ)
        return merge
```

the splitlines is not really good enough since the output of the printenv is the following
```
TERMCAP=SC|screen|VT 100/ANSI X3.64 virtual terminal:\
        :DO=\E[%dB:LE=\E[%dD:RI=\E[%dC:UP=\E[%dA:bs:bt=\E[Z:\
        :cd=\E[J:ce=\E[K:cl=\E[H\E[J:cm=\E[%i%d;%dH:ct=\E[3g:\
        :do=^J:nd=\E[C:pt:rc=\E8:rs=\Ec:sc=\E7:st=\EH:up=\EM:\
        :le=^H:bl=^G:cr=^M:it#8:ho=\E[H:nw=\EE:ta=^I:is=\E)0:\
        :li#71:co#225:am:xn:xv:LP:sr=\EM:al=\E[L:AL=\E[%dL:\
        :cs=\E[%i%d;%dr:dl=\E[M:DL=\E[%dM:dc=\E[P:DC=\E[%dP:\
        :im=\E[4h:ei=\E[4l:mi:IC=\E[%d@:ks=\E[?1h\E=:\
        :ke=\E[?1l\E>:vi=\E[?25l:ve=\E[34h\E[?25h:vs=\E[34l:\
        :ti=\E[?1049h:te=\E[?1049l:us=\E[4m:ue=\E[24m:so=\E[3m:\
        :se=\E[23m:mb=\E[5m:md=\E[1m:mh=\E[2m:mr=\E[7m:\
        :me=\E[m:ms:\
        :Co#8:pa#64:AF=\E[3%dm:AB=\E[4%dm:op=\E[39;49m:AX:\
        :vb=\Eg:G0:as=\E(0:ae=\E(B:\
        :ac=\140\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\
        :po=\E[5i:pf=\E[4i:Km=\E[M:k0=\E[10~:k1=\EOP:k2=\EOQ:\
        :k3=\EOR:k4=\EOS:k5=\E[15~:k6=\E[17~:k7=\E[18~:\
        :k8=\E[19~:k9=\E[20~:k;=\E[21~:F1=\E[23~:F2=\E[24~:\
        :F3=\E[25~:F4=\E[26~:F5=\E[28~:F6=\E[29~:F7=\E[31~:\
        :F8=\E[32~:F9=\E[33~:FA=\E[34~:kb=:K1=\EOw:K2=\EOu:\
        :K3=\EOy:K4=\EOq:K5=\EOs:kB=\E[Z:kh=\E[1~:@1=\E[1~:\
        :kH=\E[4~:@7=\E[4~:kN=\E[6~:kP=\E[5~:kI=\E[2~:kD=\E[3~:\
        :ku=\EOA:kd=\EOB:kr=\EOC:kl=\EOD:km:
```

the above output will break the current code and cause a wrong parsing of the environment variables

**Comment by xmonader** [comment]
On fresh JS8
```
In [7]: lc.bash.environ.get("LS_COLORS")
Out[7]: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'

In [8]: lc.bash.environ.get("HOME")
Out[8]: '/root'

```

Can you post your profile as a raw file?

**Comment by ahussein** [comment]
[env.txt](https://github.com/Jumpscale/jumpscale_portal8/files/616625/env.txt)

**Comment by ahussein** [comment]
as you can see the above env.txt does not contain the TERMCAP variable which means that the issue will not happen with it anymore. But you can easily reproduce if you have an environment variable set with multi lines as the code cannot handle it.

**Comment by xmonader** [comment]
Thank you :) can you retry again after pulling branch 8.1.0 ^_^ ? Because I suspect the problem was that some special characters were causing the errors not being displayed on a multiline string (Now I can start the portal fine.)

**Comment by rkhamis** [comment]
Reproduced with latest, @xmonader.
Please check
![notfixed2](https://cloud.githubusercontent.com/assets/8425762/20835373/f7e30b9e-b8a2-11e6-9acd-f171742f1757.jpg)

and 

![notfixed](https://cloud.githubusercontent.com/assets/8425762/20835401/17fe758a-b8a3-11e6-81e3-037c1d6ea2e5.jpg)

**Comment by zaibon** [comment]
This come from the systemd implementation of the process manager cuisine. I
did that cause sometime some environment variables are missing in the
process created from systemd. But it seems we are passing now too much. We
probably need to strip down to a list of predefined and relevant variables
to pass to systemd services.

**Comment by ramezsaeed** [comment]
## verified on 8.1.0rc1


```
[Service]
ExecStart=/usr/local/bin/jspython portal_start.py
Restart=always
WorkingDirectory=/opt/jumpscale8//apps/portals/main
Environment=LC_PAPER=en_US.UTF-8
Environment=LC_MONETARY=en_US.UTF-8
Environment=LESSOPEN=| /usr/bin/lesspipe %s
Environment=LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
Environment=LC_NAME=en_US.UTF-8
Environment=LC_MEASUREMENT=en_US.UTF-8
```
