### ISSUE TITLE
System space is not loaded

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_portal8#62]
from a clean install of the portal using cuisine, trying to login:
```
172.20.0.1 - - [2016-06-10 09:17:17] "GET /system/.files/css/flatTheme.css HTTP/1.1" 500 161 0.008934
path:system/.files/img/favicon.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 884, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.5/dist-packages/gevent/pywsgi.py", line 870, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 648, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale/portal/portal/auth.py", line 38, in __call__
    result = self.app(env, my_response)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale/portal/portal/PortalServer.py", line 47, in wrapper
    result = func(self, env, start_response)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale/portal/portal/PortalServer.py", line 661, in router
    sploader = self.spacesloader.getSpaceFromId(space)
  File "/opt/jumpscale8/lib/JumpScale/portal/portalloaders/LoaderBase.py", line 21, in getLoaderFromId
    raise RuntimeError("Could not find loader with id %s" % id)
RuntimeError: Could not find loader with id system
```

core8 at : c4b02e4812374b5acc12150a41058869218bec3c
portal8 at : 08702b1dde90e3d36f2053837ab87f05aa8a648a

**Comment by grimpy** [comment]
Was this at the time splitexit was broken and `wiki` != `.wiki` ?

**Comment by rkhamis** [comment]
Looks that way.
